from tkinter import *
def click(event):
    global scvalue
    text=event.widget.cget("text")
    print(text)
    if text=="=":
       if scvalue.get().isdigit():
           value=int(scvalue.get())
       else:
           try:
                value=eval(scvalue.get())
           except Exception as e:
               print(e)
               value='Error'
       scvalue.set(value)
       #screen.update()
    elif text=="c":
        scvalue.set("")
        #screen.update()
    else:
        scvalue.set(scvalue.get()+text)
        #screen.update()
root=Tk()
root.title("Calculator By depanshu")
root.geometry("445x780")
root.wm_iconbitmap("1.ico")
scvalue=StringVar()
scvalue.set("")
screen=Entry(root,textvar=scvalue,font="lucida 40 bold")
screen.pack(fill=X,ipadx=8,pady=10,padx=10)
frame1=Frame(root,bg="grey")
b=Button(frame1,text="9",font="lucida 35 bold",padx=28,pady=22)
b.pack(side=LEFT,padx=18,pady=12)
b.bind('<Button-1>',click)
b=Button(frame1,text="8",font="lucida 35 bold",padx=28,pady=22)
b.pack(side=LEFT,padx=18,pady=12)
b.bind('<Button-1>',click)
b=Button(frame1,text="7",font="lucida 35 bold",padx=28,pady=22)
b.pack(side=LEFT,padx=18,pady=12)
b.bind('<Button-1>',click)

frame1.pack()
frame1=Frame(root,bg="grey")
b=Button(frame1,text="6",font="lucida 35 bold",padx=28,pady=22)
b.pack(side=LEFT,padx=18,pady=12)
b.bind('<Button-1>',click)
b=Button(frame1,text="5",font="lucida 35 bold",padx=28,pady=22)
b.pack(side=LEFT,padx=18,pady=12)
b.bind('<Button-1>',click)
b=Button(frame1,text="4",font="lucida 35 bold",padx=28,pady=22)
b.pack(side=LEFT,padx=18,pady=12)
b.bind('<Button-1>',click)
frame1.pack()
frame1=Frame(root,bg="grey")
b=Button(frame1,text="3",font="lucida 35 bold",padx=28,pady=22)
b.pack(side=LEFT,padx=18,pady=12)
b.bind('<Button-1>',click)
b=Button(frame1,text="2",font="lucida 35 bold",padx=28,pady=22)
b.pack(side=LEFT,padx=18,pady=12)              
b.bind('<Button-1>',click)
b=Button(frame1,text="1",font="lucida 35 bold",padx=28,pady=22)
b.pack(side=LEFT,padx=18,pady=12)
b.bind('<Button-1>',click)
frame1.pack()
frame1=Frame(root,bg="grey")
b=Button(frame1,text="0",font="lucida 35 bold",padx=28,pady=22)
b.pack(side=LEFT,padx=22,pady=12)
b.bind('<Button-1>',click)
b=Button(frame1,text="-",font="lucida 35 bold",padx=28,pady=22)
b.pack(side=LEFT,padx=18,pady=12)
b.bind('<Button-1>',click)
b=Button(frame1,text="+",font="lucida 35 bold",padx=28,pady=22)
b.pack(side=LEFT,padx=18,pady=12)
b.bind('<Button-1>',click)
frame1.pack()
frame1=Frame(root,bg="grey")
b=Button(frame1,text="*",font="lucida 35 bold",padx=28,pady=22)
b.pack(side=LEFT,padx=18,pady=12)
b.bind('<Button-1>',click)
b=Button(frame1,text="=",font="lucida 35 bold",padx=28,pady=22)
b.pack(side=LEFT,padx=18,pady=12)
b.bind('<Button-1>',click)
b=Button(frame1,text="%",font="lucida 35 bold",padx=28,pady=22)
b.pack(side=LEFT,padx=18,pady=12)
b.bind('<Button-1>',click)
frame1.pack()
frame1=Frame(root,bg="grey")
b=Button(frame1,text="00",font="lucida 35 bold",padx=28,pady=22)
b.pack(side=LEFT,padx=15,pady=12)
b.bind('<Button-1>',click)
b=Button(frame1,text="c",font="lucida 35 bold",padx=28,pady=22)
b.pack(side=LEFT,padx=18,pady=12)
b.bind('<Button-1>',click)
b=Button(frame1,text="/",font="lucida 35 bold",padx=28,pady=22)
b.pack(side=LEFT,padx=17,pady=12)
b.bind('<Button>',click)
frame1.pack()
root.mainloop()